### ISSUE TITLE
Initial Page

### ISSUE THREAD

**Issue by geekingreen** [bhans23/Another-JS-Todo-List#1]
Using documentation found here: 
- https://www.w3schools.com/html/
- https://www.w3schools.com/jsref/met_document_createelement.asp
- https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
https://www.w3schools.com/jsref/prop_doc_body.asp
- https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event
- https://developer.mozilla.org/en-US/docs/Web/API/Window/alert

Create a folder called 'static'. Inside that folder create two files, 'index.html' and 'index.js'. Add a basic HTML layout to index.html and use a script tag to link to index.js. Add some JavaScript to index.js that calls alert when the window load event is fired.

**Comment by bhans23** [comment]
Please review my current push

**Comment by geekingreen** [comment]
Ya done did good! Here are a few pro tips though. 

0. Use prettier to format your code, my eyes are bleeding. (add a [.prettierrc](https://prettier.io/docs/en/configuration.html) file if you want to customize it)

1. You included your index.js script in the head tag, which is totally fine, but notice how the page doesn't render the H1 until after you clear the alert? That's because the page loads in order, from top to bottom. To alleviate this problem, simply include your scripts just above the closing </body> tag. I think with the alert it might not look rendered still but it is.

2. Your window.onload is good, you can also use `window.addEventListener('load', () => alert('Hello World'));` doing it this way would allow you to add as many listeners to the load event as you want (although in general you'd only need one).
